project:
  type: website
  output-dir: docs

website:
  title: "Paul Elvis Otto"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Paul-Elvis-Otto
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: solar
    css: styles.css



