project:
  type: website

website:
  title: "Paul Elvis Otto"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: lux
    css: styles.css



